### PR TITLE
git-tag-project-version-and-build-number 1.0.12

### PR DESCRIPTION
**Pull request by denys-meloshyn**
TagCheck

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] __I will not move an already shared step version's tag to another commit__
- [ ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by denys-meloshyn** [comment]
I think I fetched the latest version of step lib this time
```
➜  bitrise-step-git-tag-project-version-and-build-number git:(master) bitrise share start -c https://github.com/denys-meloshyn/bitrise-steplib.git
Validating Step share params...
all inputs are valid

Preparing StepLib...
StepLib found locally at: /.stepman/step_collections/1633868932/collection
For sharing it's required to work with a clean StepLib repository.
Would you like to remove the local version (your forked StepLib repository) and re-clone it? [yes/no] : yes
StepLib prepared at: /.stepman/step_collections/1636756188/collection

Next, call $ bitrise share create --tag [step-version-tag] --git [step-git-uri].git --stepid [step-id],
to add your Step to your forked StepLib repository (locally).

Important: you have to add the (version) tag to your Step's repository.

➜  bitrise-step-git-tag-project-version-and-build-number git:(master) bitrise share create --tag 1.0.12 --git https://github.com/denys-meloshyn/bitrise-step-git-tag-project-version-and-build-number.git --stepid git-tag-project-version-and-build-number
Validating Step share params...
all inputs are valid

Validating the Step...
cloning Step repo from (https://github.com/denys-meloshyn/bitrise-step-git-tag-project-version-and-build-number.git) with tag (1.0.12) to: /var/folders/j6/0fjb_49j5hl57gcprrkn39g80000gn/T/159497122
Failed to git-clone (url: https://github.com/denys-meloshyn/bitrise-step-git-tag-project-version-and-build-number.git) version (1.0.12), error: exit status 128
FATA[23:31:27] Bitrise share create failed, error: exit status 1
➜  bitrise-step-git-tag-project-version-and-build-number git:(master) bitrise share create --tag 1.0.12 --git https://github.com/denys-meloshyn/bitrise-step-git-tag-project-version-and-build-number.git --stepid git-tag-project-version-and-build-number
Validating Step share params...
all inputs are valid

Validating the Step...
cloning Step repo from (https://github.com/denys-meloshyn/bitrise-step-git-tag-project-version-and-build-number.git) with tag (1.0.12) to: /var/folders/j6/0fjb_49j5hl57gcprrkn39g80000gn/T/389621076
Step summary should be one line!
step is valid

Integrating the Step into the Steplib...
step dir in collection: /.stepman/step_collections/1636756188/collection/steps/git-tag-project-version-and-build-number/1.0.12
your Step (git-tag-project-version-and-build-number@1.0.12) has been added to the local StepLib (/.stepman/step_collections/1636756188/collection/steps/git-tag-project-version-and-build-number/1.0.12).
the StepLib changes are now prepared on branch: git-tag-project-version-and-build-number-1.0.12

Almost done! You should review your Step's step.yml file (the one added to the local StepLib),
and once you're happy with it call $ bitrise share finish

This will commit & push the step.yml into your forked StepLib repository.

➜  bitrise-step-git-tag-project-version-and-build-number git:(master) bitrise share finish
Validating Step share params...
all inputs are valid

Checking StepLib changes...
new step.yml: /.stepman/step_collections/1636756188/collection/steps/git-tag-project-version-and-build-number/1.0.12/step.yml
new step-info.yml: /.stepman/step_collections/1636756188/collection/steps/git-tag-project-version-and-build-number/step-info.yml

Submitting the changes...
pushing to your fork: https://github.com/denys-meloshyn/bitrise-steplib.git
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/denys-meloshyn/bitrise-steplib.git/'
2021/11/12 23:32:08 Bitrise share finish failed, error: exit status 1
➜  bitrise-step-git-tag-project-version-and-build-number git:(master)
```

**Comment by ofalvai** [comment]
Hey @denys-meloshyn 👋 

This section of the log tells me that something about your Git auth is not configured properly and the Bitrise CLI couldn't push your changes to your forked steplib on GitHub.

```
Submitting the changes...
pushing to your fork: https://github.com/denys-meloshyn/bitrise-steplib.git
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/denys-meloshyn/bitrise-steplib.git/'
2021/11/12 23:32:08 Bitrise share finish failed, error: exit status 1
```

**Comment by denys-meloshyn** [comment]
@ofalvai this is an old issue for me 🙂 but I found a way how to create PR's and I don't think this is a reason CI is failing)

**Comment by ofalvai** [comment]
Apologies, I thought you couldn't push your changes and what I see in this PR is not the latest state.

The CI validation is failing because of a merge conflict between this repo and your fork:

```
$ git "merge" "fork/git-tag-project-version-and-build-number-1.0.12"
CONFLICT (add/add): Merge conflict in steps/git-tag-project-version-and-build-number/step-info.yml
Auto-merging steps/git-tag-project-version-and-build-number/step-info.yml
Automatic merge failed; fix conflicts and then commit the result.
```

I checked the conflicting file and its contents are the same between the two branches, so I'm not exactly sure what causes the conflict. My best guess at this point is that your steplib fork is quite outdated (GitHub says it's 1314 commits behind on the PR branch). 

As a next step, I would retry the whole steplib share process with a clean steplib fork. Feel free to close this PR, delete your local fork, as well as the fork on GitHub, then use Bitrise CLI to share the step again.

**Comment by denys-meloshyn** [comment]
I thought that I actually cleaned everything
> Would you like to remove the local version (your forked StepLib repository) and re-clone it? [yes/no] : yes
StepLib prepared at: /.stepman/step_collections/1636756188/collection

**Comment by ofalvai** [comment]
Then I think this is the original Git authentication problem, because both your master and PR branch is behind with a thousand commits when I check on GitHub. I think the CLI was able to update the fork locally, but failed to push the update to GitHub.

**Comment by denys-meloshyn** [comment]
Ok I'll try one more time :)

**Pull request closed without merging**
