### PR TITLE
diawi-upload 0.0.1

### PR DESCRIPTION
**Pull request by deanWombourne**
Hi,

This is a tiny step which just formalises loading the diawi npm module, and then using it to upload an ipa/apk/zip to Diawi for distribution (https://www.diawi.com).

This is the first time I've done this, so let me know if you need me to change anything :)

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by deanWombourne** [comment]
Hi, I've noticed that there seems to be some corruption of the inputs in the step.yml file - the first input should be called token, but it's name has been moved down the file for some reason. The step.yml on my step repo is correct, so something is going on when I create the PR (I'm following the `bitrise share` instructions) so I'll investigate further. 

I'm expecting this (from this PR):

```
+- opts:
 +    description: |
 +      The API token for Diawi.
 +
 +      It's free to sign up and get one, just go here: https://dashboard.diawi.com/signup.
 +      You create an api token in the profile tab.
 +    is_expand: true
 +    is_required: true
 +    summary: Diawi API token
 +    title: API token
 +  token: $DIAWI_TOKEN
```

to have been this (from my step.yml):
+- opts:
 +  - token: $DIAWI_TOKEN
 +    description: |
 +      The API token for Diawi.
 +
 +      It's free to sign up and get one, just go here: https://dashboard.diawi.com/signup.
 +      You create an api token in the profile tab.
 +    is_expand: true
 +    is_required: true
 +    summary: Diawi API token
 +    title: API token
```

**Comment by viktorbenei** [comment]
Hi @deanWombourne ,

It's not corruption, it's normalization :)
If the normalized form is not correct that means the original wasn't correct, most likely you had an indentation error.

That said the normalized form looks 👍 for me, the `opts` and `api_token` keys are simply in reverse order, but as that's a hash the keys can be in any order.

**Comment by deanWombourne** [comment]
You're right - I'd got the indentation wrong, but just right enough for it to work in the local workspace editor :) I've made a 0.0.2 version which fixes this, so I'll just make a PR for that :)

Thanks!
S

**Comment by viktorbenei** [comment]
No problem and any time ;)

**Comment by deanWombourne** [comment]
Replaced by https://github.com/bitrise-io/bitrise-steplib/pull/1259 :)

**Pull request closed without merging**
