### PR TITLE
waldo-upload 0.3.0

### PR DESCRIPTION
**Pull request by eBardX**
TagCheck

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

**New Step**
Thank you for the new Step share! The CI check might will fail due to our extended validation engine. Nothing to worry about yet, we will get back to you shortly.

### CODE REVIEW

**Comment by eBardX** [comment]
Can someone tell me why the check is failing? The `Details` link takes me to a 404 page, so I am in the dark.

**Comment by simonmarton** [comment]
> Can someone tell me why the check is failing? The `Details` link takes me to a 404 page, so I am in the dark.

Hi @eBardX, thank you for the contribution! 

The CI is failing because it's missing the maintainer field in a `step-info.yml`. 
Please add the file with these contents: `maintinaer: community`

```bash
echo "maintainer: community" > steps/waldo-upload/step-info.yml
```

**Comment by eBardX** [comment]
Thanks for the info, @simonmarton. I’ve now added the maintainer field (and an icon), but still see that the check is still failing. Please advise.

**Review by simonmarton — APPROVED** [review]

**Comment by simonmarton** [comment]
Hi @eBardX, it was a security check, I've updated it. 
Merged, thanks for your patience and contribution!

**Pull request merged**
