### PR TITLE
Support for fauxpas App

### PR DESCRIPTION
**Pull request by mackoj**
This pull request replace #405 #408.

### CODE REVIEW

**Comment by viktorbenei** [comment]
Perfect, thank you for the contribution! 🚀

**Comment by mackoj** [comment]
Thanks,

**Comment by mackoj** [comment]
How can I add an icon ?

**Comment by viktorbenei** [comment]
1. Fork this repository
2. git clone it
3. add your icons (you can check other steps where it's stored - and right now we only accept `svg` icons)
4. git commit & push it
5. create a pull request

**Comment by mackoj** [comment]
Ok thanks, it will have to wait I only have a bitmap icon for the moment.

**Pull request merged**
