### PR TITLE
bitrise-step-android-info 1.0.0

### PR DESCRIPTION
**Pull request by radimvaculik**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
Thanks for sharing this step @radimvaculik ! ;)

@godrei pls do a quick review

**Comment by godrei** [comment]
Hi @radimvaculik ,

this is not a breaking issue, but in the next release please consider to use following `project_type_tags`:
- ios
- android
- xamarin

Thanks for the step!

**Comment by godrei** [comment]
@radimvaculik 

But the step id should be `android-info` instead of `bitrise-step-android-info`. Please re-share the step with the new id.

**Comment by radimvaculik** [comment]
@godrei Thanks for review my PR. I will check the step name.

**Comment by godrei** [comment]
@radimvaculik 

Re-share:

- just change the name in your [bitrise.yml](https://github.com/thefuntasty/bitrise-step-android-info/blob/master/bitrise.yml#L74)
- delete the share branch in your local steplib fork
- run `bitrise run share-this-step` again

**Pull request closed without merging**
