### PR TITLE
flowdock 0.1.1

### PR DESCRIPTION
**Pull request by scottrhoyt**

### CODE REVIEW

**Comment by viktorbenei** [comment]
Perfect, thank you for the contribution! 😉

**Comment by scottrhoyt** [comment]
No problem! How do I specify the icon displayed in the Bitrise workflow editor? I'd like to make that a bit more descriptive.

**Comment by viktorbenei** [comment]
You have to create a regular Pull Request (in your forked steplib repo create a new branch "assets", work on that branch, and then just send the PR), adding an "assets" folder in your step's folder (ex: https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/amazon-s3-upload) with your icon in it, with the name `icon.svg` (we only support SVG icons at the moment on the website) - ex: https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/amazon-s3-upload/assets .

Just put your `icon.svg` into `steps/flowdoc/assets`, commit&push&create a PR ;)

**Comment by scottrhoyt** [comment]
I did this in #232 . Let me know if it's a problem that I did it from my master branch by accident.

**Comment by viktorbenei** [comment]
No problem at all, just merged it - thank you for the icon! 😉

**Pull request merged**
