### PR TITLE
nitro-android 4.2.1

### PR DESCRIPTION
**Pull request by gaguirre**
TagCheck

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

**New Step**
Thank you for the new Step share! The CI check might will fail due to our extended validation engine. Nothing to worry about yet, we will get back to you shortly.

### CODE REVIEW

**Comment by ofalvai** [comment]
@gaguirre this PR seems to contain two new versions. One steplib PR is supposed to contain only one, can you please recreate the PR to only contain one? It seems that the next version should be 4.2.0

**Comment by gaguirre** [comment]
Hi @ofalvai 

Sure, I'll remove the `4.2.0` folder and keep the `4.2.1` version since I've made some changes and I'd prefer not to rollback them. Let me know if that's ok.

**Comment by gaguirre** [comment]
Also, I just noticed the icon is in the wrong folder. I'll fix that too and push again.
Thanks for reviewing.

**Comment by ofalvai** [comment]
This is not ideal, but it will be fine I think. There will be one skipped version number in the step library, but that's all.

**Comment by gaguirre** [comment]
I just pushed the changes. Let me know if there is anything else I should do.

**Comment by gaguirre** [comment]
Hi @ofalvai, is there anything else I should do from my side?

I've opened another PR for the iOS step. Since they have different inputs we decided to have separate steps, so we can be more explicit on which parameters are required and which ones optional.

**Comment by gaguirre** [comment]
Hi @ofalvai, I'm working on a tutorial on how to use Nitro with Bitrise and it would be great for me if this PR is merged, so I can finish and publish it.
Thanks in advance!

**Review by ofalvai — APPROVED** [review]
Apologies for the long delay, LGTM!

**Pull request merged**
