### PR TITLE
telegram-notify v1.0.1

### PR DESCRIPTION
**Pull request by mcaldas**
TagCheck

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by mcaldas** [comment]
Any update on this?

**Comment by koral--** [comment]
Your tag is not in semver format. Here is the guideline: https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md#version-naming-convention

**Comment by mcaldas** [comment]
> Your tag is not in semver format (there is extra `v` prefix). Here is the guideline: https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md#version-naming-convention

because of the `v` ?

**Comment by koral--** [comment]
Exactly.

**Comment by mcaldas** [comment]
> Exactly.

🤦🏻‍♂️ 
Can i update this PR or need to create a new one? If so, how?

**Comment by koral--** [comment]
I think the easiest way is to create new, valid tag and share the step again in new PR.

**Comment by trapacska** [comment]
Hey @mcaldas !

Thanks for the PR, but please try to follow @koral-- 's suggestions as he were right.
The v in the version is not a valid version format for our system.

Thanks in advance!

**Comment by mcaldas** [comment]
> Hey @mcaldas !
> 
> Thanks for the PR, but please try to follow @koral-- 's suggestions as he were right.
> The v in the version is not a valid version format for our system.
> 
> Thanks in advance!

@trapacska @koral--  done in #1777

**Pull request closed without merging**
