### PR TITLE
cocoapod-key 1.0.2

### PR DESCRIPTION
**Pull request by igorcferreira**
TagCheck

This PR aims to fix an [issue reported](https://github.com/FutureWorkshops/bitrise-step-cocoapod-key/issues/3), giving more flexibility to the step.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by mobilestar1** [comment]
Hello Bitrise team, Can you please apprvove this PR so that many teams can work with cocoapods-keys with Bitrise?
Thanks.

**Comment by igorcferreira** [comment]
@mobilestar1 If this step is important for your workflow, you can use the `git::` prefix on your YML file for now (until this update is published):

```
- git::https://github.com/FutureWorkshops/bitrise-step-cocoapod-key.git@master:
    title: Check certificate
    inputs:
    - project_name: "$PROJECT"
    - podfile_path: "./$PROJECT"
    - keys: "KEY_A|KEY_B"
    - values: "$FIRSTKEY|$SECOND_KEY"
```

**Comment by mobilestar1** [comment]
@igorcferreia It works like a charm. Thanks.

**Comment by BirmacherAkos** [comment]
@godrei Please merge the PR.

**Pull request merged**
