### PR TITLE
microsoft-teams-integration 1.0.1

### PR DESCRIPTION
**Pull request by amrfarid140**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [*] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [*] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [*] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [*] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
Hi @amrfarid140 ,

Thanks for the PR!

As this is a new step we'll do a bit more thorough check, just to make sure everything's 👍 (e.g. categories, URLs, step dev guideline compliance, ...)

Once the first version is accepted future updates will go faster as we'll only have to check the diffs ;)

**Comment by kdobmayer** [comment]
Hi @amrfarid140 ,

Did you check the step with a working Microsoft Team server?
Please add a test workflow into the `bitrise.yml`:

```yml
    - path::./:
        title: Step test
        inputs:
        - INCOMING_WEBHOOK_URL: <copy_the_webhook_url_here>
```

Then run this test locally with the following command: `bitrise run test`

**Comment by amrfarid140** [comment]
Hey @kdobmayer ,

What do you mean Microsoft Team Server. This step is intended for Microsoft Teams (Chat App), do you mean the chat app ?

Moreover, I ran ``` bitrise run test ``` prior to making this pull request and it ran successfully.

let me know if you need more info.

Thanks 😃

**Comment by kdobmayer** [comment]
The `bitrise run test` command will run the test defined in the `bitrise.yml`. When you created the new step a basically empty test generated (without any valid inputs):

```
   - path::./:
        title: Step Test
        description: |-
          The example input has a default value,
          you can overwrite it if you want to, just like we did below,
          but the step would use the default value specified in the `step.yml`
          file if you would not specify another value.
        run_if: true
        inputs:
        - example_step_input: Example Step Input's value
```

You should fill the `inputs` section with the proper input fields and values for testing if the message successfully sent to Microsoft Teams. You should check if the message arrived also. If seems to me from the source code of the step that currently it is not working properly.

**Comment by amrfarid140** [comment]
@kdobmayer I've made the requested changes and tested it with Microsoft Teams, see below : 

- [Screenshot of Microsoft teams receiving message](https://ibb.co/jGQZ2x)

- [Screenshot of test completion ](https://ibb.co/eHPNpc)

**Comment by kdobmayer** [comment]
Great!

I sent you a Pull Request with some changes. The most important one is that the current code is not parsing the environment variables into the `Config` variable because a function call is missing.
You can check that by setting the `BITRISE_GIT_BRANCH` env var to any value, it won't be displayed in the message. The PR contains the fix for that.

**Comment by amrfarid140** [comment]
Hey @kdobmayer ,

Thanks for the pull request. I have merged it and updated this pull request. Let me know if there is anything else.

**Comment by kdobmayer** [comment]
LGTM!

**Pull request merged**
