### PR TITLE
Infisical secrets 0.0.1

### PR DESCRIPTION
**Pull request by Willt123**
TagCheck

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ *] __I will not move an already shared step version's tag to another commit__
- [ (] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ *] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ *] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ *] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

**New Step**
Thank you for the new Step share! The CI check might will fail due to our extended validation engine. Nothing to worry about yet, we will get back to you shortly.

### CODE REVIEW

**Comment by Willt123** [comment]
Hi All, 

Im not sure what else I need to do here? I've signed the CLA but its not coming up as signed.
Any assistance would be appreciated?

**Comment by Willt123** [comment]
Please can I get some help from someone at bitrise? maybe @godrei 
CLI is saying not signed but I signed it weeks ago and when I click the link it says already signed. 

Thanks

**Comment by ofalvai** [comment]
Hey @Willt123, I'm checking the step.yml, but the referenced git repo gives me a 404: https://github.com/CodeFishStudio/bitrise-step-infisical-secrets

Are you sure the repo is public?

**Comment by Willt123** [comment]
Hey @ofalvai 

Apologies, we renamed the repository, I thought I managed to correct all of the references. 
https://github.com/CodeFishStudio/infisical-bitrise-step

I'll correct the bitrise.yml as well

**Comment by godrei** [comment]
Hi @Willt123 ,
as far as I see the step hasn't been updated yet.
I'm closing this PR for now, please update the step and open a StepLib PR with the updated step version based on this guide: https://devcenter.bitrise.io/en/steps-and-workflows/developing-your-own-bitrise-step/sharing-steps-with-all-bitrise-users.html#fixing-issues-in-a-steplib-pull-request

**Pull request closed without merging**
