### PR TITLE
aws-device-farm-file-deploy 0.0.3

### PR DESCRIPTION
**Pull request by fadookie**
- Docs update

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
Awesome, thank you @fadookie for the update!

Just one thing. We're in the middle of normalizing the type and project tags, can you please update your step.yml to the new tags/project types? Docs: https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md#step-grouping-convention

We did normalize your previous step.yml in this steplib repo (https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/aws-device-farm-file-deploy/0.0.2/step.yml#L18), so if you're OK with those, feel free to just copy paste it into your repo's step.yml, and share it as a new step verison.

Sorry for the inconvenience and let us know if you have any questions!

**Comment by viktorbenei** [comment]
I just sent a PR with the normalization: https://github.com/peartherapeutics/bitrise-aws-device-farm-file-deploy/pull/12

**Comment by fadookie** [comment]
will re-submit

**Comment by viktorbenei** [comment]
Thank you! 😊

**Comment by fadookie** [comment]
https://github.com/bitrise-io/bitrise-steplib/pull/999

**Pull request closed without merging**
