### PR TITLE
update-homebrew 0.0.1

### PR DESCRIPTION
**Pull request by chrisfuller**
TagCheck

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [X] __I will not move an already shared step version's tag to another commit__
- [X] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [X] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [X] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [X] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by godrei** [comment]
Hi, @chrisfuller would not be it an option to add this feature to the brew install step: https://github.com/bitrise-steplib/steps-brew-install

**Comment by chrisfuller** [comment]
Hi @godrei. This step was created for the cases where [the brew install step](https://github.com/bitrise-steplib/steps-brew-install) is not used, such as when step dependencies are specified via `deps:` in workflows.

**Comment by godrei** [comment]
@chrisfuller very god catch,  we do not call `brew update` before we would install a brew dependency: https://github.com/bitrise-io/bitrise/blob/master/bitrise/dependencies.go#L339-L360

This case: I will create a ticket to fix this issue however, I still think that this is not something a step supposed to fix. We will fix this issue and this will make this step unnecessary.

As a workaround, you can use this step from its git source: https://github.com/bitrise-io/bitrise/blob/master/_examples/tutorials/steps-and-workflows/bitrise.yml#L65, until we fix this issue.

**Comment by godrei** [comment]
Closing as we did not receive a reply - @chrisfuller please let us know if we can help with anything!

**Pull request closed without merging**
