### PR TITLE
Yarn

### PR DESCRIPTION
**Pull request by jonoirwinrsa**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
How did you share this step? Through the Bitrise CLI? If yes, what's the output of `bitrise version`?

Asking because the latest CLI should properly handle step version separation - your PR still includes 2 versions of the step

**Comment by jonoirwinrsa** [comment]
Yeah through the CLI. Bitrise version is 1.4.2.

I'll run it again but commit and push the changes manually instead of running `bitrise share finish` this time. I think that maybe its fetching v0.0.1 (of my step) from github... 

Again: apologies for the admin!

**Comment by viktorbenei** [comment]
Did you share it "manually" calling stepman directly? 

I see you have a bitrise.yml in your repo with the share-this-step workflow, you should simply run that and that should handle the sharing for you. No other calls should be required just: bitrise run share-this-step

**Comment by viktorbenei** [comment]
Of course manual sharing is OK too, just wanted to mention this for the future 😉

**Comment by jonoirwinrsa** [comment]
I've just been following the steps that are returned by running `bitrise share`

**Comment by jonoirwinrsa** [comment]
Will try out `bitrise run share-this-step` now

**Comment by viktorbenei** [comment]
Yeah, we should update those.. Sorry for the confusion/inconvenience

**Pull request closed without merging**
