### PR TITLE
steps-app-gallery-deploy v1.0.0

### PR DESCRIPTION
**Pull request by ferPrieto**
### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by trapacska** [comment]
Hi @ferPrieto !

I found some problems with this PR:
- There is already an app-gallery-deploy step shared: https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/app-gallery-deploy with multiple versions. 
- This version looks like using a different step ID originally it was `app-gallery-deploy` -> and now `appgallery-deploy`. 
- Also the issuer is different: https://github.com/FutureMind/bitrise-step-huawei-app-gallery-apk-distribution.git (originally)
- This step.yml was not shared with out stepman. Please follow the guide: https://devcenter.bitrise.io/contributors/sharing-steps-with-all-bitrise-users/

**Comment by ferPrieto** [comment]
@trapacska this app-gallery-deploy step is the verified one (official Huawei step), hence it's got different ID, different issuer and so force. 
The step.yml was shared with out stepman. 

Can you double check and discuss it with your colleagues?

**Comment by trapacska** [comment]
@ferPrieto if you compare the two files: https://github.com/bitrise-io/bitrise-steplib/pull/2857/files#diff-52e5526231d842346761fc6353d084d733e32be0f3a057d49c7af5d46567ef95 (from this PR) and the one from the step repo: https://github.com/ferPrieto/steps-app-gallery-deploy/blob/main/step.yml then you can see the files are identical. 

When you release it with stepman(https://devcenter.bitrise.io/contributors/sharing-steps-with-all-bitrise-users/#sharing-with-the-bitrise-share-command) then a slightly modified version of step.yml will be committed to this PR. It will have `source` object for example, like here: https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/amazon-s3-deploy/3.1.1/step.yml#L13-L15

The reason I closed this PR because the share with stepman requires a new PR. (will be on different branch)

**Comment by ferPrieto** [comment]
Apologies for the misunderstanding @trapacska 
Last time I used the stepman I ended up skipping the last step because github did not recognise my credentials when I executed. I had to change my local configuration and it seems to work now 👍 

I've raised a new PR. Thanks for the support!

**Pull request closed without merging**
