### PR TITLE
firebase-app-distribution 0.5.0

### PR DESCRIPTION
**Pull request by guness**
TagCheck

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by guness** [comment]
basically fixes https://github.com/guness/bitrise-step-firebase-app-distribution/issues/12 using 
```curl -sL firebase.tools | bash``` instead of ```npm -g install firebase-tools```.

**Comment by xuzhe** [comment]
> basically fixes [guness/bitrise-step-firebase-app-distribution#12](https://github.com/guness/bitrise-step-firebase-app-distribution/issues/12) using
> `curl -sL firebase.tools | bash` instead of `npm -g install firebase-tools`.

Do you think install firebase tools globally is required?

**Comment by guness** [comment]
Well, basically it is already installed on most of the stacks on bitrise, globally. so this curls makes a quick check, and installs it only if missing.

**Comment by brittonjg** [comment]
@guness how long does it usually take for the new version to appear in Bitrise?

**Comment by guness** [comment]
@brittonjg couple of mins after the PR merged.

if your task is urgent, you can use 
```
- git::https://github.com/guness/bitrise-step-firebase-app-distribution.git:
```
instead of on bitrise.yml

```
- firebase-app-distribution:
```

until PR is merged.

**Comment by Scarafone** [comment]
This did solve my issue as well. Any ETA when it will be approved and merged?

**Comment by guness** [comment]
@viktorbenei any help ?

**Comment by Abdul-Hannan** [comment]
please merge it @viktorbenei  @trapacska

**Comment by viktorbenei** [comment]
I'll ping the tooling team also assigned the review to them.

**Pull request merged**
