### PR TITLE
sentry-dsym-upload 1.0.0

### PR DESCRIPTION
**Pull request by SimonRice**
TagCheck

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

**New Step**
Thank you for the new Step share! The CI check might will fail due to our extended validation engine. Nothing to worry about yet, we will get back to you shortly.

### CODE REVIEW

**Comment by SimonRice** [comment]
`bitrise run test` currently attempts to run everything without env variables.  In other words, `sentry-cli --auth-token upload-dif --org --project --disable_check true` is run, with all parameters missing, which fails.  I'm totally open to any good ways to resolve this one.

**Comment by trapacska** [comment]
@SimonRice Why is it draft? 🙂

**Comment by SimonRice** [comment]
@trapacska only reason was down to the CI failing - since it now passes I'm very happy to open it up.

Also, I'm very open to any suggestions on a good way of doing `bitrise run test`.

**Comment by sylank** [comment]
Hey @SimonRice,

We would really like to accept your PR.
Could you write an integration test for this step? I want you to create a test scenario that will clone a demo repository and runs the step on it.

Here an example scenario. It should be implemented inside your step's `bitrise.yml`

1. Clone the example repository from GitHub with a regular git command `git clone`
2. Use the `- path::./:` step to run your step. Use the input variables to give input
3. Then check your step's output. Does it export an env-var? If not then save the output into a file and check it with a command-line application like `grep`.

Example steps:
https://github.com/bitrise-steplib/steps-go-list/blob/41f6579de7b821bffbbeecca2b96bbab8e7d51a1/bitrise.yml#L10
https://github.com/andrewmarmion/bitrise-step-firebase-dsym-upload/blob/master/bitrise.yml

**Comment by SimonRice** [comment]
Thank you so much for the guidance @sylank - I'll let you know how this all goes and get back to you if I need any further help.  These examples should be brilliant starting points though!

**Comment by adborbas** [comment]
Hi @SimonRice, Could you please open an other PR once you have applied the changes you wanted? I'll close this one.

**Comment by SimonRice** [comment]
Of course @adborbas - sorry I've been slow to do this on my part!

**Comment by tc** [comment]
Has sentry dsym uploading been incorporated into bitrise directly now?

Hard to find documentation around this.

**Pull request closed without merging**
