### PR TITLE
cocoaseeds-install step 1.0.0

### PR DESCRIPTION
**Pull request by Frugghi**
[CocoaSeeds](https://github.com/devxoul/CocoaSeeds)

### CODE REVIEW

**Comment by viktorbenei** [comment]
Thanks, we'll review it ASAP!

**Comment by godrei** [comment]
Hi @Frugghi ,
step's summary field will appear on [integrations page](https://www.bitrise.io/integrations), step's descritpion field is visible on bitrise.io workflow editor, that's why we provide more detailed description in `description` field, not in `summary` field.
It's not a critical issue, but in next version it would be great to follow this best practice.

By the way it looks great to me, thanks for the contribution!

**Comment by Frugghi** [comment]
@godrei thank you for pointing that out, I will fix it next time!

**Comment by viktorbenei** [comment]
Yep, the only thing is that you should: provide a short summary for `summary` and a longer description for `description`, other than that it's all good :)

Merged - thanks for the contribution!

**Pull request merged**
