### PR TITLE
Telegram notify 1.0.3

### PR DESCRIPTION
**Pull request by mcaldas**
TagCheck

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by mcaldas** [comment]
Any update on this?

**Comment by godrei** [comment]
Hi @mcaldas ,
step icon should take place at the step's root directory, in your case: `STEPLIB_REPO/steps/telegram-notify`.
Please update your pr.

**Comment by mcaldas** [comment]
@godrei updated, let me know if its ok

**Comment by godrei** [comment]
@mcaldas now it looks great to me! thanks for the new step version!

**Comment by mcaldas** [comment]
@godrei  why i dont see the latest version of the step in bitrise workflow editor?

**Comment by godrei** [comment]
@mcaldas because of i did not realize that the tag was moved before i merged your pr.
Because i merged this step version the steplib deploy workflow failed (as it run full validation and checks every step version - commit hash).
The deploy workflows are running fine now, so your step should be available from now.

**Comment by godrei** [comment]
Hi @mcaldas once we merge a steplib pr, the steplib deploy workflow takes ~20min.
I can see the `Send Telegram Message` step's `1.0.3` version in my sandbox project.
You may need to full refresh your browser to invalidate browser caches.

**Pull request merged**
