### PR TITLE
AppGallery Deploy Verified Step

### PR DESCRIPTION
**Pull request by ferPrieto**
TagCheck

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [yes] __I will not move an already shared step version's tag to another commit__
- [yes] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [yes] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [yes] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [yes] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by ferPrieto** [comment]
The CLA has been signed already. Can you check why this has not been reflected?

**Comment by Janos-vrancsik** [comment]
Hey @ferPrieto 

As we discussed in private, I can see that the CLA has been signed already, so hereby I confirm for the team that's reviewing it that the PR can be merged if there are no other outstanding issues.

**Comment by imrekel** [comment]
hey @ferPrieto `step-info.yml` is missing from https://github.com/ferPrieto/bitrise-steplib/tree/master/steps/appgallery-deploy. Could you please add it (with just a single `maintainer: community` line, similarly to https://github.com/ferPrieto/bitrise-steplib/blob/master/steps/appaloosa/step-info.yml)?

**Comment by imrekel** [comment]
@ferPrieto ignore my previous comment, I've added the missing file

**Review by imrekel — APPROVED** [review]

**Pull request merged**
