### PR TITLE
sonarqube-scanner 3.0.1.733.0

### PR DESCRIPTION
**Pull request by koral--**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
@godrei & @trapacska please review!

**Comment by godrei** [comment]
Hi @koral-- ,

please use semantic versioning (MAJOR.MINOR.PATCH) for your step.
To apply your fixed version please re-share your step by:

- close this PR
- delete your`sonarqube-scanner-3.0.1.733.0` branch in your steplib fork
- share the step again

**Comment by koral--** [comment]
@godrei I can change it to 1.0.0 but that version scheme is intentional. 
`3.0.1.733` is a version of Sonar Scanner CLI embedded in the step, it matches upstream version number: https://github.com/SonarSource/sonar-scanner-cli/releases/tag/3.0.1.733
Trailing `0` is a patch number of a step itself.

With this scheme, users know in advance which scanner CLI version is used. There is no need to browse changelogs. E.g. [RxJavaProGuardRules](https://github.com/artem-zinnatullin/RxJavaProGuardRules) uses the same scheme.

What do you think now?

If it is strictly required to use semantic versioning, shouldn't it be mentioned in the documentation?
I could not find such requirement in http://devcenter.bitrise.io/bitrise-cli/create-your-own-step/ and pages which can be reached from there like [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md).

**Comment by godrei** [comment]
@koral-- thanks for the clarification! 

When one of our steps is a wrapper around a tool, we provide an option to specify the tool's version and the step manages to download the desired version (maybe it is not an option in your case...).

Maybe you could mention the embedded `Sonar Scanner CLI`'s version in the step title as an alternative solution.

If you want to use this version, we will need some more time, to validate if this kind of version is working well with our system, since this step would be the first one, which does not use 3 component semantic versioning.

**Comment by koral--** [comment]
I've planned to add an input with scanner version name before I read the guideline. 

There is a rule: [Do not use submodules, or require any other resource downloaded on-demand](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md#do-not-use-submodules-or-require-any-other-resource-downloaded-on-demand).
Scanner is not available in official apt-get repositories.

But if you suggest that this rule can be violated I will add input for version name. Scanner CLI ZIP has about 0.5 MB and is officially hosted on bintray so download issues should occur very rarely.

I'll add input for version and send new PR.
Thanks.

**Comment by viktorbenei** [comment]
That sounds wonderful, thank you @koral-- ! :)

**Pull request closed without merging**
