### PR TITLE
appaloosa 1.2.0

### PR DESCRIPTION
**Pull request by chrsvl**
Fix:
+ description was breaking when user put quotes and special characters.

Feature:
+ add support for a new changelog field.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
Please update your step so that it includes a test and audit.
Right now this is not a show stopper, but we might change this in the future for new step versions.

**Comment by chrsvl** [comment]
You are right, tests for the win!

**Comment by viktorbenei** [comment]
And for encouraging / helping contributions for the project/step ;)

**Comment by viktorbenei** [comment]
Merged, will be available on bitrise.io too in ~10 mins, after the caches expire (if you wouldn't see it after that please try to reload the page a couple of times, to clear the browser's cache too).

Thanks for the contribution! 🚀 ;)

**Pull request merged**
