### PR TITLE
Magicpod ui test 0.54.1

### PR DESCRIPTION
**Pull request by nkns165**
TagCheck

We'd like to deprecate this step and replace with the new one from https://github.com/bitrise-io/bitrise-steplib/pull/2531, so this PR should be merged after #2531 .
I'm not sure if it meets the condition of abandoned policy.  We won't add new features to this step, but we can support the users. We have changed icon and description explicitly so that users can notice the new step.

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by koral--** [comment]
Why not just increment major version?

**Comment by nkns165** [comment]
> Why not just increment major version?

- Since we set version number following our main service, we'd like to keep it if possible (not mandatory, I think)
- Can we block automatic version up for users who have "Always latest" setting by incrementing major version?

**Comment by lpusok** [comment]
There is now an option to lock to major version (https://devcenter.bitrise.io/steps-and-workflows/step-inputs/#locking-a-step-to-a-major-or-minor-version), but people who selected Always latest previously will be updated. Should we continue with adding the new step?

**Comment by koral--** [comment]
IMHO it is partially philosophical question. I don't know this tool and have no idea how much effort is needed to migrate existing workflows.
If migration is relatively easy and a new step version prints info what to do when it encounters the old config it is an argument for not creating a separate step.

Apart from that if new step will be added, steplib supports another way to mark step deprecated (other than changing the icon).
You can add `step-info.yml`, like that: https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/wetransfer/step-info.yml

**Comment by nkns165** [comment]
Thank you for your detailed comments.  Let me discuss within our company.  I will reply next week.

**Comment by nkns165** [comment]
> Thank you for your detailed comments. Let me discuss within our company. I will reply next week.

As the new step was already merged, I will deprecate the old step.
I updated `step-info.yml` according to @koral-- 's advice and got some error from CI.  I hope it was fixed by the next commit (removing quotations).

**Comment by nkns165** [comment]
Could anybody let me know about the CI failure, please?

**Comment by trapacska** [comment]
sorry for the delay @nkns165

**Comment by nkns165** [comment]
oh, the error was resolved? thanks

**Pull request merged**
