### PR TITLE
bitbucket-server-post-build-status 0.0.12

### PR DESCRIPTION
**Pull request by teameh**
TagCheck

Fix: Allow Multiple builds for one Hash Commit  - [KageRiyuu](https://github.com/KageRiyuu)

### New Pull Request Checklist

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by teameh** [comment]
Re-pushed commit with cla-signed comitter email. All good now?

**Comment by ofalvai** [comment]
Hey @teameh 👋 

The CI validation is failing because of a merge conflict between this repo and your fork:

```
$ git "merge" "fork/bitbucket-server-post-build-status-0.0.12"
CONFLICT (add/add): Merge conflict in steps/bitbucket-server-post-build-status/step-info.yml
Auto-merging steps/bitbucket-server-post-build-status/step-info.yml
Automatic merge failed; fix conflicts and then commit the result.
```

I checked the conflicting file and its contents are the same between the two branches, so I'm not exactly sure what causes the conflict. My best guess at this point is that your steplib fork is quite outdated (GitHub says it's 768 commits behind on the PR branch). 

As a next step, I would retry the whole steplib share process with a clean steplib fork. Feel free to close this PR, delete your local fork, as well as the fork on GitHub, then use Bitrise CLI to share the step again.

**Comment by teameh** [comment]
Thanks @ofalvai . I've rebased, fixed the conflict and force-pushed. Seems fine now.

**Review by ofalvai — APPROVED** [review]
Perfect, everything is valid now. Thank you for the contribution @teameh

**Pull request merged**
