### PR TITLE
post-jira-comment-with-build-details 0.1.1

### PR DESCRIPTION
**Pull request by dag-io**

### CODE REVIEW

**Comment by godrei** [comment]
Looks great to me! 
What do you think @viktorbenei?
Thanks @dag-io !

**Comment by viktorbenei** [comment]
@dag-io are you sure that you don't want this step to run for Pull Request builds (https://github.com/bitrise-io/bitrise-steplib/pull/435/files#diff-687020de9cbe47e8d7720f9a1c04a541R18) ?

**Comment by dag-io** [comment]
@viktorbenei Yes because I'm afraid it would generate "duplicates" builds. I thought the build for the **push** would be the one published in JIRA. What do you think ?

**Comment by viktorbenei** [comment]
Can be, it's not an issue at all, just want to make sure that this is what you intended to do ;)

**Comment by viktorbenei** [comment]
you might also want to set more specific `type_tags`, but that's also up to you

**Comment by viktorbenei** [comment]
if you say it's good as it is, we can merge it

**Comment by viktorbenei** [comment]
you can of course fix/change this after sharing too, by sharing a new version ;)

**Comment by viktorbenei** [comment]
merged - thanks for the contribution! We'd suggest you to use a more specific `type_tags` in your next version, something like `jira`, `issue-tracker`, to make it easier to find your step in the lib

**Comment by dag-io** [comment]
Changed applied here : bitrise-io/bitrise-steplib#437

**Comment by viktorbenei** [comment]
Awesome, thank you! (just merged it 😉 )

**Pull request merged**
