### PR TITLE
gist-bash-script-runner 1.0.0

### PR DESCRIPTION
**Pull request by jsauve**
Hopefully this will be my PR that actually makes it in. I gave it a new ID and and repo location.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [X] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [X] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [X] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [X] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by kdobmayer** [comment]
Hi @jsauve 

Thanks for the new step! I sent a PR, please check it out.

Maybe a new input would be useful to specify script(s) to run from the given gist if somebody doesn't want to run all of them.

**Comment by jsauve** [comment]
@kdobmayer, that's a good idea! I'll think about how to implement. Maybe by index. (Perhaps in a format that's similar to how you specify to a printer driver which range of pages to print. i.e "1-3, 5-6, 8")

**Comment by viktorbenei** [comment]
One more thing, although I just saw this and I'm not 100% sure about it: if you remove the commit from the `raw` url of the gist that AFAIK points to the latest version of the script.

E.g.: https://gist.github.com/viktorbenei/8900fefd8338559e4c4ccb34fbcfe37d

- clicking raw the URL is: https://gist.githubusercontent.com/viktorbenei/8900fefd8338559e4c4ccb34fbcfe37d/raw/d7a78d0695a28bb598ec54c0b80b894c4e2768d5/install-bitrise-cli.sh
- BUT https://gist.githubusercontent.com/viktorbenei/8900fefd8338559e4c4ccb34fbcfe37d/raw/install-bitrise-cli.sh also works!

**Comment by kdobmayer** [comment]
Hi @jsauve ,
Can you please update your PR based on the PR I sent you?

@viktorbenei , there can be multiple file in a gist, and you have to know the filenames if you want to get the raw urls. Downloading the mentioned URL works only if a new input is implemented to specify the name of the scripts to run.
I would go with cloning the gist, because it ensures that the gists are up-to-date.

**Comment by jsauve** [comment]
Thanks @kdobmayer. I'll get back to this soon, hopefully! I definitely like the cloning idea.

**Comment by kdobmayer** [comment]
Hi @jsauve 

I'm closing this PR, please open a new PR when you updated the step.

**Comment by viktorbenei** [comment]
Of course if you'd have any questions @jsauve feel free to ask it here, we're happy to answer/help! ;)

**Comment by jsauve** [comment]
No problem. I'll do another PR at some point. I'm manually injecting my step for now. Just haven't had time to get back to improving this.

**Pull request closed without merging**
