### PR TITLE
Feature: Swiftformat Linting Verification Step

### PR DESCRIPTION
**Pull request by dmiluski**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

## References:
[SwiftFormat](https://github.com/nicklockwood/SwiftFormat)
[SwiftForrmat Step Repo](https://github.com/dmiluski/bitrise-step-swiftformat)

## Inspired by Prior Art:
https://github.com/kimdv/bitrise-step-swiftlint

## Goal:
Given SwiftFormat is a solution primarily targeted for code formatting, it lacks the enforcement protection for a repo. Although git hooks can make for autoformatting to occur automatically, it also is not a requirement to perform changes/PRs.

This is an attempt to provide a format enforcement step to ensure the code adhears to a format definition.

### CODE REVIEW

**Comment by dmiluski** [comment]
Thanks folks for administrating this service.

Any thoughts on testing?

Generally speaking this is just taking a swift format file and inspecting to see if there are any files which file to adhere to rules. I looked to follow the example set by existing swfitlint step, but wasn't able to understand how it was tested.

Locally I verified this ran as a custom step passing/failing as expected via:
`bitrise run --config bitrise.yml --json-params-base64 eyJ3b3JrZmxvdyI6InByaW1hcnkifQ==`

As to the Bitrise CI test failure, I was wondering if there was feedback as to what this failed as I was unable to view it?

**Comment by dmiluski** [comment]
Ping?

**Comment by dmiluski** [comment]
Hi @trapacska,

Reaching out in case you have time next week as to whether this is something that could be evaluated/integrated?

**Comment by dmiluski** [comment]
Hi @godrei , seeing if you had time if I could get an eye on this?

**Comment by Szabadember** [comment]
@dmiluski I reviewed it, I will discuss it with the @godrei tomorrow and get back to you ASAP.

**Comment by trapacska** [comment]
Thank you for the new step @dmiluski !
Happy Building! 🚀

**Pull request merged**
