### PR TITLE
xcodebuild 0.0.4

### PR DESCRIPTION
**Pull request by chrisfuller**
TagCheck

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [X] __I will not move an already shared step version's tag to another commit__
- [X] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [X] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [X] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [X] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by godrei** [comment]
@chrisfuller why do you need this step, or to be more precise, what is the problem with xcode-archive and xcode-test steps?

**Comment by chrisfuller** [comment]
Hi @godrei. The intention is to provide an alternative approach. The existing steps are great, this step simply offers an alternative for anyone interested in this style. The differentiating goals for this step are to not use Go and to handle various use cases (building/testing/archiving/etc) in a single step (as opposed to separate steps).

Note that improved input titles are pending in a subsequent release as can be seen on `master`:

https://github.com/chrisfuller/bitrise-step-xcodebuild/blob/master/step.yml

Can this PR please be merged as is in order to keep the release history clean? And will submit another PR for `v0.0.5`.

Thank you.

**Comment by richard-bogdan-bitrise** [comment]
Did not find any issue. @trapacska pls check.

**Comment by godrei** [comment]
@chrisfuller the point of using steps is the user does not need to know how the underlying tool works. They just need to configure steps. 

Other than that might the hardest thing after the different xcodebuild command calls are to collect the generated outputs (xcarchive, ipa, test results...), which is not solved by this step.

It only exposes `XCRESULT_BUNDLE_PATH`, which exists only in the case of test-related xcodebuild calls.

**Comment by godrei** [comment]
Closing as we did not receive a reply - @chrisfuller  please let us know if we can help with anything!

**Pull request closed without merging**
