### PR TITLE
wetransfer 0.0.5

### PR DESCRIPTION
**Pull request by kawaiseb**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by kawaiseb** [comment]
**Come on bitrise team** :) you like to make me suffer !

**Comment by viktorbenei** [comment]
:D thanks for the update @kawaiseb - I swear once the initial version is accepted updates will go way faster, as we only have to check the diffs ;)

**Comment by godrei** [comment]
Hi @kawaiseb ,
thanks for the fixes and for this new step!
It looks great to me!

**Comment by koral--** [comment]
Step has been removed from steplib: https://github.com/bitrise-io/bitrise-steplib/blob/d3581bdf1de00ddbbe0f0c7113f75d855312e8b1/steps/wetransfer/step-info.yml

**Pull request merged**
