### PR TITLE
Code signing setting patch 1.0.1

### PR DESCRIPTION
**Pull request by j796160836**
TagCheck

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by j796160836** [comment]
Hi, I wonder that why CI Tag the failed tags?
I have no permission to see the error log, thanks.

**Comment by koral--** [comment]
PR should contain only one commit.
https://github.com/bitrise-io/bitrise-steplib#important

**Comment by j796160836** [comment]
Oh, Sorry. Here is my first time write the step plugins. I squash that.

**Comment by j796160836** [comment]
Oh, CI it fail again. 🤔

**Comment by BirmacherAkos** [comment]
Hi @j796160836,
Sorry for the late response.

The CI is failing because of the none supported `type_tag`s
Screenshot 2019-11-04 at 15 15 15


Here is the list of the supported type_tags:
https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md#step-grouping-convention

---

- Please remove the `pbxproj` and the `xcodeproj` tags.
- Close this PR. _As you will need to share a new version of the step._
- Create a new release and share the new version again.

**Comment by j796160836** [comment]
Hi, I updated the new pull request below
https://github.com/bitrise-io/bitrise-steplib/pull/2302
Please check it, thanks.

**Pull request closed without merging**
