### PR TITLE
nowsecure-auto-analysis 0.1.2

### PR DESCRIPTION
**Pull request by sp3nx0r**
TagCheck

Fixes API call issue to NowSecure as raised by @DamienBitrise. https://github.com/sp3nx0r/bitrise-step-nowsecure-auto-analysis/issues/1

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [X] __I will not move an already shared step version's tag to another commit__
- [X] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [X] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [X] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

**New Step**
Thank you for the new Step share! The CI check might will fail due to our extended validation engine. Nothing to worry about yet, we will get back to you shortly.

### CODE REVIEW

**Comment by godrei** [comment]
Hi @sp3nx0r ,
it seems this step is already shared with step id: `bitrise-step-nowsecure-auto-analysis`: https://github.com/bitrise-io/bitrise-steplib/tree/master/steps/bitrise-step-nowsecure-auto-analysis.

Changing step id is not recommended, as existing users have the step with the old id in Bitrise config files (bitrise.yml), they would not see this update as a step update, but as a new step.

**Comment by trapacska** [comment]
@sp3nx0r please see @godrei's comment and do a fresh re-share 🙂 🚀

**Comment by matteinn** [comment]
Any luck here @sp3nx0r ?

**Comment by pmegremis** [comment]
Any update on this @sp3nx0r ?

**Pull request closed without merging**
