### PR TITLE
appaloosa 1.3.0

### PR DESCRIPTION
**Pull request by chrsvl**
Adding .apk support.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
Perfect, thank you for the contribution! 🚀

**Comment by chrsvl** [comment]
Thanks Viktor! Sorry for the trouble earlier :(

**Comment by viktorbenei** [comment]
Just a note: you could define a default value for the binary path input, separate by pipe (`|`) char - https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md#inputs-which-can-accept-a-list-of-values

E.g. it could be `$BITRISE_IPA_PATH|$BITRISE_APK_PATH` - and you just ignore the one which is empty

**Comment by viktorbenei** [comment]
or, alternatively, you could introduce a second input, for APK

**Comment by chrsvl** [comment]
Thanks, will do 👍

**Pull request merged**
