### PR TITLE
Add new step: xcode-project-info 1.0.1

### PR DESCRIPTION
**Pull request by tadija**
Ok, here's another take on #430 and #431. :)

### CODE REVIEW

**Comment by viktorbenei** [comment]
Perfect!

Last question: are you sure that you want to use this ID for your step? Once it's shared there's no option to change it, only to share it under a new name and deprecate the old one - to not to break user workflows who already use the step.

**Comment by tadija** [comment]
Thanks for notice, but that was mostly the reason I named in a little bit broader sense - as sometimes later, it can be extended for reading project info other then just build or version number.

**Comment by viktorbenei** [comment]
Fair enough, and thank you for the contribution! Your step is now available in the Step Lib - it'll appear on bitrise.io too in 5-10 minutes, once the caches pick up the change ;)

**Comment by tadija** [comment]
Awesome!

Thanks for the very quick feedback on this.

**Comment by viktorbenei** [comment]
Thanks for the Step! 😉

**Pull request merged**
