### PR TITLE
git-tag-project-version-and-build-number 1.0.4

### PR DESCRIPTION
**Pull request by ned1988**
TagCheck

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by hkellaway** [comment]
hello! i'm relying on the update `1.0.4` version of this step - is it possible to merge?

**Comment by igorcferreira** [comment]
@hkellaway I don't know if you are still depending on the update version of this step. But, just to let it registered here:
It is possible to link directly to the step Github page at a specific branch/tag. Just add the following to your YML file (adjusting necessary variables):

```
- git::https://github.com/ned1988/bitrise-step-git-tag-project-version-and-build-number.git@master
	title: Tag repository
	inputs:
	- bitrise_tag_xcodeproj_path: "./"
	- bitrise_tag_info_plist_path: "./$PROJECT/Support Files/Info.plist"
	- bitrise_tag_format: "v_VERSION_(_BUILD_)"
	- use_lightweight_tag: "no"
```

I know it is not the ideal solution, but it may unblock an workflow

**Comment by hkellaway** [comment]
thanks @igorcferreira ! i wasn’t aware of that & will keep it as a workaround. appreciate the tip

**Comment by BirmacherAkos** [comment]
@trapacska Please merge the PR.

**Pull request merged**
