### PR TITLE
jira-issue-status-update 0.1.0

### PR DESCRIPTION
**Pull request by MiSikora**
TagCheck

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by godrei** [comment]
Hi @MiSikora ,
thanks for the new step.

I was wondering whether the functionality of this step is already implemented in the [Update JIRA issues field](https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/update-jira-issue-field/1.0.2/step.yml) step.

What is the key difference you started to implement a new step?

**Comment by MiSikora** [comment]
Hi @godrei!

Linked step is used for updating fields on the issue like `Fix version`, `Components`, `Labels`, etc. It uses `PUT /rest/api/3/issue/{issueIdOrKey}` endpoint to do this (or in case of this step `v2` but it is irrelevant).

This step is used to perform transition of the step which cannot be done by simple update. That is - dragging and dropping issue in the columns of the active sprint. So it is used to change it from i.e. `Code review` status to `In tests` status in order to inform QA engineers about new tasks or w/e. It uses `POST /rest/api/3/issue/{issueIdOrKey}/transitions` endpoint to do this.

**Comment by MiSikora** [comment]
Actually, nevemind. I think I'm wrong here and this can be set via mentiond `PUT` endpoint as well. I'll double check it later and close this PR if it so.

**Comment by godrei** [comment]
@MiSikora thanks foe the info! This case I gonna wait with the merge.

**Comment by MiSikora** [comment]
Thanks! I'll let you know when I find out. :)

**Comment by MiSikora** [comment]
@godrei 
Ok, changing status cannot be done with the linked step. JIRA endpoint ignores transitions on a mentioned `PUT` request so it looks like this step is not redundant.

**Comment by koral--** [comment]
@godrei the same question was asked in Mar 2018: https://discuss.bitrise.io/t/how-to-update-a-nested-field-using-update-jira-issues-field-step/4353/3 ;)

**Pull request merged**
