### PR TITLE
set-gem-home 0.0.2

### PR DESCRIPTION
**Pull request by chrisfuller**
TagCheck

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [X] __I will not move an already shared step version's tag to another commit__
- [X] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [X] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [X] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [X] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by lpusok** [comment]
This seems to reflect the previous way of recommended caching of ruby gems, which is now updated: https://devcenter.bitrise.io/builds/caching/caching-ruby-gems/

**Comment by godrei** [comment]
Hi @chrisfuller is the purpose of this step ruby gem caching? If so, pls update the step based on our latest guide: https://devcenter.bitrise.io/builds/caching/caching-ruby-gems/

**Comment by godrei** [comment]
@chrisfuller the step repo's release history is not necessarily dependent on the StepLib releases. Unfortunately, this happens with Bitrise maintained steps as well sometimes, we release changes in the step repo, but it turns out that the release was not successful, this case we fix the issue, create a new release in the step repo and share the correct version of the step to the StepLib.

We do not merge step versions which have known issues, as by default if a user adds a step to his/her workflow, the step will be locked to the current version, this way might we will have users locked on 0.0.2 version of this step.

Please close this PR and open a new one with the fixed version of the step.

**Comment by godrei** [comment]
Closing as we did not receive a reply - @chrisfuller please let us know if we can help with anything!

**Pull request closed without merging**
