### PR TITLE
nvm 1.3.1

### PR DESCRIPTION
**Pull request by Almouro**
TagCheck

This adds `set -e` to ensure build fails if `nvm` step fails (see https://github.com/Almouro/bitrise-nvm-step/pull/15/files)

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by godrei** [comment]
Hi @Almouro ,
thank you for the new Step version, looks good to me!

**Comment by enagorny** [comment]
@Almouro After this changes this step starts to fail for me

```
+------------------------------------------------------------------------------+

| (2) nvm                                                                      |
+------------------------------------------------------------------------------+
| id: nvm                                                                      |
| version: 1.3.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2022-07-20T16:35:13Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 15037  100 15037    0     0  58716      0 --:--:-- --:--:-- --:--:-- 62136
=> Downloading nvm from git to '/Users/vagrant/.nvm'

=> Cloning into '/Users/vagrant/.nvm'...
* (HEAD detached at FETCH_HEAD)
  master
=> Compressing and cleaning up git repository
=> Appending nvm source string to /Users/vagrant/.profile
=> bash_completion source string already in /Users/vagrant/.profile
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
=> You currently have modules installed globally with `npm`. These will no
=> longer be linked to the active version of Node when you install a new node
=> with `nvm`; and they may (depending on how you construct your `$PATH`)
=> override the binaries of modules installed with `nvm`:
/usr/local/lib
├── @ionic/cli@6.19.0
├── appcenter-cli@2.10.8
├── cordova@11.0.0
├── corepack@0.10.0
└── react-native@0.68.1
=> If you wish to uninstall them at a later point (or re-install them under your
=> `nvm` Nodes), you can remove them from the system Node as follows:
     $ nvm use system
     $ npm uninstall -g a_module
=> Close and reopen your terminal to start using nvm or run the following to use it now:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | nvm (exit code: 3)                                            | 13.49 sec|
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/almouro/bitrise-nvm-step/issues            |
| Source: https://github.com/almouro/bitrise-nvm-step                          |
+---+---------------------------------------------------------------+----------+
```


previously it was working fine
```
+------------------------------------------------------------------------------+

| (2) nvm                                                                      |
+------------------------------------------------------------------------------+
| id: nvm                                                                      |
| version: 1.3.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2022-07-15T15:04:27Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 57 13527   57  7748    0     0  33363      0 --:--:-- --:--:-- --:--:-- 35058
100 13527  100 13527    0     0  57957      0 --:--:-- --:--:-- --:--:-- 60932
=> Downloading nvm from git to '/Users/vagrant/.nvm'

=> Cloning into '/Users/vagrant/.nvm'...
=> Compressing and cleaning up git repository
=> Appending nvm source string to /Users/vagrant/.profile
=> bash_completion source string already in /Users/vagrant/.profile
N/A: version "14.18.3 -> N/A" is not yet installed.
You need to run "nvm install 14.18.3" to install it before using it.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
=> You currently have modules installed globally with `npm`. These will no
=> longer be linked to the active version of Node when you install a new node
=> with `nvm`; and they may (depending on how you construct your `$PATH`)
=> override the binaries of modules installed with `nvm`:
/usr/local/lib
├── @ionic/cli@6.19.0
├── appcenter-cli@2.10.8
├── cordova@11.0.0
├── corepack@0.10.0
└── react-native@0.68.1
=> If you wish to uninstall them at a later point (or re-install them under your
=> `nvm` Nodes), you can remove them from the system Node as follows:
     $ nvm use system
     $ npm uninstall -g a_module
=> Close and reopen your terminal to start using nvm or run the following to use it now:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
N/A: version "14.18.3 -> N/A" is not yet installed.
You need to run "nvm install 14.18.3" to install it before using it.
Switching to working directory: /Users/vagrant/git
Found '/Users/vagrant/git/.nvmrc' with version <14.18.3>
Downloading and installing node v14.18.3...
Downloading https://nodejs.org/dist/v14.18.3/node-v14.18.3-darwin-x64.tar.xz...
#=#=#                                                                         

#                                                                          1.8%
#####                                                                      7.5%
################                                                          23.0%
###########################                                               37.6%
###################################                                       49.9%
#############################################                             63.1%
#######################################################                   77.1%
###########################################################               83.2%
################################################################          89.9%
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
2022-07-15 15:04:46.178 xcodebuild[2361:9585] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-07-15 15:04:46.179 xcodebuild[2361:9585] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Now using node v14.18.3 (npm v6.14.15)
Creating default alias: default -> 14.18.3 (-> v14.18.3 *)
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | nvm                                                           | 24.64 sec|
+---+---------------------------------------------------------------+----------+
```

for now I'm downgrading back to 1.3.0

**Comment by enagorny** [comment]
@godrei do you know if it is possible to stick exactly with `1.3.0` which was working for me before? 
UI doesn't allow it for me
image

**Comment by enagorny** [comment]
please ignore me, found answer in https://github.com/Almouro/bitrise-nvm-step/issues/16

**Pull request merged**
