### PR TITLE
perfecto-upload 0.0.2

### PR DESCRIPTION
**Pull request by sreevatsa-ramya**
TagCheck

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [ ] __I will not move an already shared step version's tag to another commit__
- [ ] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [ ] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

**New Step**
Thank you for the new Step share! The CI check might will fail due to our extended validation engine. Nothing to worry about yet, we will get back to you shortly.

### CODE REVIEW

**Comment by trapacska** [comment]
@sreevatsa-ramya could you please commit the step-info.yml also as described here? https://github.com/bitrise-io/bitrise-steplib/pull/2549#pullrequestreview-430206104

Thanks!

**Comment by sreevatsa-ramya** [comment]
Hi,

I have committed the step-info.yml in 0.0.2 version. The same code which is
here - https://github.com/PerfectoCode/Bitrise_Perfecto_FileUpload is
pushed. Please pardon my knowledge but help me with how to re-submit it.

Best Regards,
Sree

**Comment by trapacska** [comment]
@sreevatsa-ramya I see. Sorry for not mentioning that the repo where you should push the step-info.yml file is actually your bitrise-steplib fork repo. (https://github.com/PerfectoCode/bitrise-steplib/tree/perfecto-upload-0.0.2)

Steps to do it at this point:
- Remove step-info.yml file from your repo(https://github.com/PerfectoCode/Bitrise_Perfecto_FileUpload)
- Release and share a new version(0.0.3) (also close this PR)
- Commit the step-info.yml file to your steplib fork repo, to the new version branch: (It will be available after you shared the new version of the step) https://github.com/PerfectoCode/bitrise-steplib/tree/perfecto-upload-0.0.3

Please let me know If you need further explanation. Sorry for the inconvenience! 🚀

**Comment by sreevatsa-ramya** [comment]
Hi Tamas,

No sorries please. I am new to this and so required more details. Have
followed your instructions and have done a new commit. Please let me know
if this is fine.

BR,
Sree

**Pull request closed without merging**
