### PR TITLE
detekt 1.0.0

### PR DESCRIPTION
**Pull request by misaelmt**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
Thanks for the PR @misaelmt , we'll check it ASAP! :)

**Comment by viktorbenei** [comment]
Note: as this is a new step it might take a longer time for us to review it. Once the first version is accepted subsequent updates will be faster to get accepted as we'll only check the diffs.

**Comment by misaelmt** [comment]
Thanks @viktorbenei ! No problem, I understand that you (and I, as a Bitrise user) want to maintain a high quality standard :)

**Comment by viktorbenei** [comment]
Exactly! ;)

Note: you can already use your own step if you want to, by specifying its git clone URL directly! See: http://devcenter.bitrise.io/bitrise-cli/steps/#step-referenceid-format 
specifically the `git::` syntax. If you'd have any questions just let us know! ;)

**Comment by kdobmayer** [comment]
Hi @misaelmt !

Thanks for the new step! I sent you a Pull Request with the requested changes, but maybe it would be better to recreate the repository to avoid storing a large binary file.

**Pull request closed without merging**
