### PR TITLE
bitrise-step-firebase-app-distribution 0.8.0

### PR DESCRIPTION
**Pull request by guness**
TagCheck

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

**New Step**
Thank you for the new Step share! The CI check might will fail due to our extended validation engine. Nothing to worry about yet, we will get back to you shortly.

### CODE REVIEW

**Comment by simonmarton** [comment]
Hi @guness, thank you for the contribution! 

The CI is failing because it's missing the maintainer field in a `step-info.yml`. 
Please add the file with these contents: `maintainer: community`

```bash
echo "maintainer: community" > steps/waldo-upload/step-info.yml
```

**Comment by guness** [comment]
> Hi @guness, thank you for the contribution!
> 
> The CI is failing because it's missing the maintainer field in a `step-info.yml`.
> Please add the file with these contents: `maintainer: community`
> 
> ```shell
> echo "maintainer: community" > steps/waldo-upload/step-info.yml
> ```

I can see it here:

https://github.com/guness/bitrise-steplib/blob/master/steps/firebase-app-distribution/step-info.yml
or should I put this file into the step itself?

**Comment by simonmarton** [comment]
Hi @guness,

Looks like there's a mismatch in the step id in this PR, could you open a new PR with the id `firebase-app-distribution` please?

**Comment by guness** [comment]
> Hi @guness,
> 
> Looks like there's a mismatch in the step id in this PR, could you open a new PR with the id `firebase-app-distribution` please?

OK, opened a new one:

#2674

**Pull request closed without merging**
