### PR TITLE
set-gradle-info 1.0.0

### PR DESCRIPTION
**Pull request by manuelgon47**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by godrei** [comment]
Hi @manuelgon47 ,
thanks for the new step!

May i ask you if did you have seen the [change-android-versioncode-and-versionname](https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/change-android-versioncode-and-versionname/0.9.0/step.yml) step? It seems that your step solves the same problem.

I see that your step:

- handles version code offset, which is really useful and missing from the other step
- exports the versions and the gradle file path

Would not it be an option to create a PR with these updates to the existing step, since it would be confusing for the Bitrise users if multiple steps existed for the same functionality?

**Comment by manuelgon47** [comment]
Of course, I decided to create a new step instance of create a PR to the existing step because I feel more confortable writing bash instance of GO, but I'll work on it tonight.

**Comment by godrei** [comment]
@manuelgon47 ,
thanks for your quick response and understanding! Let me know if you need help, to create these changes!

**Comment by manuelgon47** [comment]
Hi friend I pull request a few minutes ago.
I have had a complicated days, thats why I took more days.

Regards!

**Pull request closed without merging**
