### PR TITLE
Giphy

### PR DESCRIPTION
**Pull request by Almouro**
Hi guys,

Small step to get a gif from Giphy and save it into a $GIF_URL :)
Very useful to send slack messages :D

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by bloodrabbit** [comment]
/giphy party hard !!
giphy-6

**Comment by viktorbenei** [comment]
Awesome idea 😂

We'll do a thorough first review, as this is the very first version of the step, but it shouldn't take more than 24h, we'll do it asap. After that updates will be way quicker as we only have to scan through the diffs

**Comment by viktorbenei** [comment]
I'll do a review, @godrei pls do one too

**Comment by viktorbenei** [comment]
Step.yml looks good to me

**Comment by viktorbenei** [comment]
Step id is also good imo

**Comment by viktorbenei** [comment]
I'd rather read the words param as an env var in the python script (https://github.com/Almouro/bitrise-giphy-step/blob/master/step.sh#L3) to avoid bash/shell parameter issues, but that can be done in an future update, and the code doesn't have any security issues, so I definitely 👍

**Comment by viktorbenei** [comment]
The code is fairly trivial, so I guess we can skip the second review for now - @godrei feel free to comment if you'd not agree, but I think it's safe to accept as the first version

**Comment by viktorbenei** [comment]
First version merged, should be available on the UI too in about 10 mins, once the caches refresh 😉

Thanks for this awesome step @Almouro! 

@bloodrabbit schedule a blog post if you like 😉

**Comment by Almouro** [comment]
Yaaay! Thanks guys! :D

**Pull request merged**
