### PR TITLE
codified-security-bitrise 2.0.0

### PR DESCRIPTION
**Pull request by adamivancza**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by godrei** [comment]
Hi @adamivancza ,
it seems you renamed your step repo's tags (for example: `1.0.0` become `Bitrise1.0.0`).
This breaks your step, since bitrise stored your step versions with the original tags.

This will break every workflow which uses this step directly (not through the StepLib, as the StepLib has a built in CDN/cache protection for these cases) also our steplib audit fails, since it can not git clone the step repo with the original versions.

Please revert every tag name updates, otherwise, we need to remove the step from the steplib.

**Comment by adamivancza** [comment]
Hey @godrei,

thanks for the heads up - gonna investigate what happened there!

**Comment by adamivancza** [comment]
@godrei restored all the tags - sorry for the inconvenience!

**Comment by godrei** [comment]
@adamivancza that was fast, thanks!

**Pull request merged**
