### PR TITLE
fauxpasapp 0.1.3

### PR DESCRIPTION
**Pull request by mackoj**

### CODE REVIEW

**Comment by godrei** [comment]
Hi @mackoj ,
i think you shared a previous version of the step check out the file changes section header:
`steps/fauxpasapp/0.1.1/step.yml`

Also the changes are missing, check out the previous PR's conversation:
`https://github.com/bitrise-io/bitrise-steplib/pull/405`

**Comment by mackoj** [comment]
I made a mistake and I forget to update the version number.

**Comment by godrei** [comment]
Hi @mackoj ,
can you please check again, what @viktorbenei wrote about `is_always_run ` and `run_if ` in this [conversation](https://github.com/bitrise-io/bitrise-steplib/pull/405)?

Usually `is_always_run : true` and `run_if : true` is used by `notification` steps. If you set that inputs to true, your setp will run even if previous step (like git-clone) fails.

**Comment by mackoj** [comment]
I have made this modification last Friday I will update this PR soon.

**Comment by mackoj** [comment]
Il will re-share thanks

**Pull request closed without merging**
