### PR TITLE
Git tag project version and build number 1.0.1

### PR DESCRIPTION
**Pull request by ned1988**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by godrei** [comment]
Hi @ned1988 ,

When you shared your step's first version (1.0.0), the related tag (1.0.0) where put on the commit: `e2cb1a7eff22ceca25843e0eaa65adf489e9dc1a`. 

When we merge a step version into the steplib, we save the version's (version tag's) commit hash into the steplib as well: https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/git-tag-project-version-and-build-number/1.0.0/step.yml#L12.
This guarantees that a step version always means the same state of the step.

You recently removed your version tag (1.0.0) from the original commit: `e2cb1a7eff22ceca25843e0eaa65adf489e9dc1a` and put to a new commit: `7d6ce6e2e1d0d03db147e296ea86d863731655c1`. You also put another tag on that tag (1.0.1).

Moving the git tag on an already shared step version is not allowed, please put back the 1.0.0 to the original commit.

If the first version has an issue, just fix the issue create a new tag and share that version.

Also please submit a step version in a single commit.

**Comment by godrei** [comment]
@ned1988 let me know if you need any help and thanks for the step!

**Comment by ned1988** [comment]
Hi @godrei ! Ok I removed tag `1.0.0` and put it back to `e2cb1a7eff22ceca25843e0eaa65adf489e9dc1a`. Sorry for making so many troubles 🙂

**Comment by godrei** [comment]
@ned1988  thanks for the fix.

To be honest, we would need to highlight this tagging requirement more.

Regarding to the new version (1.0.1) please create a new clean share (since the current pr modifies 2 versions of the step). To create a fresh steplib pr, please:

- remove the `git-tag-project-version-and-build-number-1.0.1` branch from your steplib fork
- rerun the [share workflow](https://github.com/bitrise-core/bitrise-plugins-step/blob/master/create/templates/bitrise.yml.gotemplate#L62) with the new version (1.0.1) of the step

I will close this pr and wait for the fresh one.

**Pull request closed without merging**
