### PR TITLE
Swiftlint 0.4.2 😴😴😴

### PR DESCRIPTION
**Pull request by kimdv**
@viktorbenei and @deanWombourne if this I wrong, I'm just going to sleep ! xD

And I'm really sorry for all the work @viktorbenei !
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
And what if it's not wrong? :D

**Comment by kimdv** [comment]
I will open a beer and celebrate 🎉🎉🎉🎉

**Comment by kimdv** [comment]
🍻

**Comment by viktorbenei** [comment]
🍻 and thanks for the quick fix! ;)

**Comment by kimdv** [comment]
And sorry for the extra work! 
If I ever meet you in IRL, I will buy you a beer!

**Comment by viktorbenei** [comment]
No problem at all but I'm of course open for a beer if we meet IRL ;)

**Comment by deanWombourne** [comment]
Just checked this on my workflow and it's working perfectly - thanks (and sorry, it was my yml beginner's mistake in the first place ;)

**Comment by viktorbenei** [comment]
No problem at all, we should have caught it during review.. Will improve on that! 😊

**Pull request merged**
