### PR TITLE
Appaloosa

### PR DESCRIPTION
**Pull request by chrsvl**
Fixing 1.2.0 version (problem in step.sh)

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [ ] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [ ] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by viktorbenei** [comment]
Hi,

Please re-share this step in a way that only one commit/version is included.
Probably the easiest way is:

1. open your fork of this bitrise-steplib repo
2. delete the `appaloosa` branch there
3. re-share the step (no change required)

**Comment by chrsvl** [comment]
Will do, what a mess...

**Comment by viktorbenei** [comment]
yeah.. btw we just pushed the fixed Bitrise CLI v1.4.2 - https://github.com/bitrise-io/bitrise/releases/tag/1.4.2

if you install this version it'll take care of this automatically ;)

**Comment by viktorbenei** [comment]
it's not available in brew yet, so you have to install it with the `curl` method you can see on the release's page (`curl` + `chmod`)

**Pull request closed without merging**
