### PR TITLE
Perfecto upload 1.0.0

### PR DESCRIPTION
**Pull request by sreevatsa-ramya**
TagCheck

### What to do if the build fails?

At the moment contributors do not have access to the CI workflow triggered by StepLib PRs. In case of a failed build, we ask for your patience. Maintainers of Bitrise Steplib will sort it out for you or inform you if any further action is needed.

### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by tothszabi** [comment]
@sreevatsa-ramya this PR will introduce breaking changes in a patch version update. User tend to lock steps to the major version and this change could potentially break builds as users will automatically receive it. 

Usually we advise to release the breaking changes in a major version upgrade.

**Comment by shams-ahmed** [comment]
@sreevatsa-ramya any update on changing the version increment?

**Comment by sreevatsa-ramya** [comment]
Hi,

Please let me know exactly what I should do

Best Regards,
Sree

**Comment by shams-ahmed** [comment]
Update the version from `0.0.10` to `1.0.0`

**Comment by sreevatsa-ramya** [comment]
Hi,

I have updated the version number and shared the step. But not able to see
the changes on the bitrise steplib. I could see the changes on my repo -
https://github.com/PerfectoCode/Bitrise_Perfecto_FileUpload and have also
released 1.0.0.

Any suggestions on how to fix this?

Sree

**Comment by shams-ahmed** [comment]
@sreevatsa-ramya try running `bitrise run share-this-step`

**Comment by sreevatsa-ramya** [comment]
This is done successfully. But I am not getting a pull request on bitrise

Sree

**Comment by shams-ahmed** [comment]
PR merged now.. thanks!

**Pull request closed without merging**
