### PR TITLE
aws-device-farm-runner 0.0.4

### PR DESCRIPTION
**Pull request by fadookie**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by fadookie** [comment]
looks like I forgot to pull my steplib fork master again :/

**Comment by viktorbenei** [comment]
Please use the latest CLI to share your step, which prevents sharing multiple versions in a single PR.

If you'd want to create this PR manually, please do not share more than one version in a single PR!

**Comment by viktorbenei** [comment]
You can find the recommended sharing (through the CLI) steps here: https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml#L82

**Comment by fadookie** [comment]
@viktorbenei yeah I just forgot to pull my steplib fork again before sharing, fixed in https://github.com/bitrise-io/bitrise-steplib/pull/787

**Comment by viktorbenei** [comment]
No problem ;)

**Pull request closed without merging**
