### PR TITLE
change-value 1.0.0

### PR DESCRIPTION
**Pull request by BOOMik**

### CODE REVIEW

**Comment by viktorbenei** [comment]
Did you share it again?

The error is:

```
Failed to clone step (https://github.com/BOOMik/step_change_value.git): Commit hash doesn't match the one specified for the version tag. (version tag: 1.0.0) (expected commit hash: 8a9481ebe474510243e9fe7fda62d2dcba63731e) (got: 3b93f5d00eb7036dc9539b3c8e1f6e380123bb8b)
```

**Comment by viktorbenei** [comment]
Can you please just drop 1.0.0 and share it again as 1.0.1 ?

**Comment by viktorbenei** [comment]
by drop I mean ignore it, don't do anything with it

**Comment by BOOMik** [comment]
I fix tag. Please try again

**Pull request closed without merging**
