### PR TITLE
release-notes-extractor 0.0.1

### PR DESCRIPTION
**Pull request by ashrafDoubleO7**
### New Pull Request Checklist

*Please mark the points which you did / accept.*

- [x] __I will not move an already shared step version's tag to another commit__
- [x] I read the [Step Development Guideline](https://github.com/bitrise-io/bitrise/blob/master/_docs/step-development-guideline.md)
- [x] I have a test for my Step, which can be run with `bitrise run test` (in the step's repository)
- [x] I did run `bitrise run audit-this-step` (in the step's repository - note, if you don't have this workflow in your `bitrise.yml`, [you can copy it from the step template](https://github.com/bitrise-steplib/step-template/blob/master/bitrise.yml).)
- [x] I read and accept the [Abandoned Step policy](https://github.com/bitrise-io/bitrise-steplib#abandoned-step-policy)

### CODE REVIEW

**Comment by ashrafDoubleO7** [comment]
@godrei Please check it out

**Comment by trapacska** [comment]
Hi @ashrafDoubleO7 !

What is it differs from git-commit-changelog? Looks familiar to me. 😊

**Comment by ashrafDoubleO7** [comment]
Hi @trapacska!

I'm aware of `git-commit-changelog`, it's actually very useful is some cases, but there is a major difference between the two steps.
 `git-commit-changelog` relies on commit messages between tags as a source of input, while `release-notes-extractor` uses the current repository changelog file to extract the release notes.
The latter is highly efficient when you already have a changelog that is maintained and if you're in a team with no certain taste for "tags" and not necessarily relying on commit messages.

**Comment by BirmacherAkos** [comment]
@godrei Could you please merge the PR?

**Comment by ashrafDoubleO7** [comment]
@BirmacherAkos @godrei Thank you guys for merging this!

I'm facing an issue, the script was supposed to run a nodejs script that does the actual work, now when I include the step it reports a failure saying it can't find the script.

I'm not exactly sure what I'm doing wrong, is it something involving the working directory?
I'm basically running the node script from the bash script like:
node script.js $changelog_file_path $trim_markdown_output

Thanks.

**Comment by BirmacherAkos** [comment]
Hi @ashrafDoubleO7 

I think the problem is that the working directory is not the same as the directory where the step will be downloaded.

The Bitrise CLI downloads the steps to a temporary directory ( /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/bitrise666960107/step_src ) but the working directory is where your project located (  /Users/Vagrant/git ).

Try this in the script.sh

```
#!/bin/bash
set -ex

echo "* Changelog file path: $changelog_file_path"
# Execute the extractor script
echo "* Executing the release notes extractor"

THIS_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
node "$THIS_SCRIPT_DIR/release_notes_extractor.js" $changelog_file_path $keep_markdown_output

exit 0

```

**Comment by ashrafDoubleO7** [comment]
@BirmacherAkos Thank you! that was actually the issue, I've tried the "test" flow on my machine switching to another directory and it gave the same error I reported error, but after making the changes you suggested, now the script is being read from the script directory.

I've submitted a new [https://github.com/bitrise-io/bitrise-steplib/pull/2341](PR)

**Pull request merged**
